[package]
name = "first-light"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
analytic-renderer = { path = "../../crates/renderer" }
analytic-field = { path = "../../crates/field" }
spatial-math = { path = "../../crates/math" }
world-state = { path = "../../crates/world" }
world-simulation = { path = "../../crates/simulation" }
wgpu = { version = "=30.0.1", default-features = false, features = ["std", "wgsl", "dx12", "vulkan"] }
winit = { version = "=0.30.13", default-features = false, features = ["rwh_06", "x11", "wayland"] }
pollster = "=1.0.1"

[lints]
workspace = true
